name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NEXT_PUBLIC_API_TO_MOCK: https://api.example.com
  NEXT_PUBLIC_JSON_PLACEHOLDER_API: https://jsonplaceholder.typicode.com

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: yarn nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - name: Installing Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Deriving appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Connecting to NX Cloud
        run: yarn nx-cloud record -- nx format:check
        continue-on-error: true

      - name: Checking affected changes
        run: yarn nx affected -t lint test build

      - name: Run affected e2e tests
        run: yarn nx affected -t e2e-ci
