import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { BaselimeRum } from '@baselime/react-rum';

import type { ReactNode } from 'react';
import type { Metadata } from 'next';

import BrowserMswProvider from '../providers/BrowserMswProvider';
import QueryProvider from '../providers/QueryProvider';
import Navigation from '../components/Navigation';
import { albertSans, notoSans } from '../lib/fonts';
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Welcome to fe-next',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className={`${notoSans.className} ${albertSans.variable}`}>
      <body>
        <BrowserMswProvider>
          <QueryProvider>
            <BaselimeRum
              apiKey={process.env.NEXT_PUBLIC_BASELIME_API_KEY as string}
              enableWebVitals={process.env.NODE_ENV === 'production'}
              service="nx-next-mongo-contentful"
              fallback={
                <h1 className="fixed bottom-2 left-2 text-red-700">
                  BaselimeRum error occured
                </h1>
              }
            >
              <header className=" bg-slate-900">
                <Navigation />
              </header>
              <main className="max-w-5xl mx-auto">{children}</main>
              <footer></footer>
              <ReactQueryDevtools initialIsOpen={false} />
            </BaselimeRum>
          </QueryProvider>
        </BrowserMswProvider>
      </body>
    </html>
  );
};

export default RootLayout;
